---
title: "ADRG Template Update Proposal : An Open-Source Edition"
author: "OSDocuMeta Working Group"
format: revealjs
---


# About the WG

## Add background and mission statement - see Home page of website.

- Background
- Mission

# About Us

## Pics of us and 2 sentences about each of us

- Lovemore Gavaka (Co-Lead)
- Joel Laxamana (Co-Lead)
- Nicholas Masel
- Steven Haesendonckx
- ... add others

- Chris Price (Sponsor)

# Where we are

## Share the current ADRG template we have now and how we want to update the template to include open-source metadata - Lovemore

- Current ADRG Template
- How we want to update the template

## Current ADRG from Pinnacle 21 vs an ADRG where Open-source submission was used, 

## list out the differences and note these differecnes as the updates we want to make to the current ADRG template to be Open-Source friendly.

# Where we're going

## List out all of the tables in this ADRG, here, that we can automate and generate sourcing available metadata

  - 1.2 Study Data Standards and Dictionary Inventory (Can this come from the TS SDTM domain?)
  - 3.1 Core Variables (come from the define.xml specificaions)
  -4.2 Data Dependencies (may need to some code scraping to read through each ADaM program and identify any other ADaMs being sourced in to create the ADaM)
  -5.2 Analysis Datasets (read in all of the .xpts in the submission package to extract the metadata for each ADaM to fill in this table)
  -6.2 Issues Summary (extract report from P21)
  -7.2 ADaM Programs (read in all of the .xpts in the submission package to extract the list of ADaMs and it’s label for each ADaM to fill in this table)
  -7.3 Analysis Output Programs (this one may be tricky as there are many study specific Selection Criteria to include)
  -7.4 Proprietary R Packages (Joel has some code for this, in R, essentially using SessionInfo() and {renv})
eCTD structure.

- With these listed updates we want to make, we can utilize metadata to help fill in this information in the ADRG 

## Challenge the file format delivered to the FDA, not only .pdf, but can we additionally submit .qmd files (or other file formats) as well so that the ADRG can be reproduced on the Agency side to help better click on code from the ADRG to help execute. Note : eCTD specifications say we can submit .qmd for analysis, but can we also submit it as a form of ADRG documentation.

# A new tool to automate ADRG generation

## Do we want to bring up the possibility of creating an open-source package for this to help automate the use of metadata in the ADRG documentation.

- {osdocumeta}

# The End. Questions? 